name: logincodelab
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.19.5 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  intl: ^0.17.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
